/**
 * Bundle the Vercel serverless function's own source into ONE self-contained
 * JS file, so Vercel never has to resolve our TypeScript source tree at runtime.
 *
 * Why this exists — the failure it fixes:
 *
 *   Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/backend/router'
 *     imported from /var/task/api/[...path].js
 *
 * `@vercel/node` TRACES imports (nodeFileTrace) rather than bundling them, so
 * `import app from '../backend/router'` survived verbatim into the deployed
 * output. That import cannot resolve there for two independent reasons:
 *
 *   1. `backend/**` are .ts files — Node's ESM loader cannot execute TypeScript.
 *   2. The root package.json is `"type": "module"`, and extensionless specifiers
 *      do not resolve under ESM even when a .js file is present.
 *
 * `includeFiles: "backend/**"` cannot fix either one: copying .ts sources next
 * to the function still leaves nothing Node can load.
 *
 * The fix: pre-bundle to `api/_bundle.js` and have the committed entry point
 * re-export it. Vercel's own docs specify that files in `api/` beginning with an
 * underscore are NOT turned into functions, so the bundle is a payload, not a
 * second (12-function-cap-consuming) endpoint.
 *
 * Ordering is load-bearing and was verified against a real deploy log: the
 * function build ("Installing dependencies... Using TypeScript") runs AFTER
 * `buildCommand` completes, so a file generated here is present when the
 * function is packaged. `api/_bundle.js` is therefore gitignored build output.
 *
 * Only RELATIVE imports are inlined. Runtime npm packages stay external and are
 * resolved from node_modules the normal way — bundling mongoose/express would
 * bloat the function and break their dynamic requires.
 */
import { build } from 'esbuild';
import { existsSync, readFileSync } from 'node:fs';

const ENTRY = 'backend/router.ts';
const OUT = 'api/_bundle.js';

// Everything in `dependencies` stays external: these are real npm packages that
// exist in the deployed node_modules. Read from package.json rather than a
// hardcoded list so a new dependency cannot silently get inlined.
const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const external = Object.keys(pkg.dependencies ?? {});

if (!existsSync(ENTRY)) {
  console.error(`[buildVercelFunction] entry missing: ${ENTRY}`);
  process.exit(1);
}

console.log(`[buildVercelFunction] bundling ${ENTRY} → ${OUT}`);
console.log(`[buildVercelFunction] external: ${external.join(', ')}`);

await build({
  entryPoints: [ENTRY],
  outfile: OUT,
  bundle: true,
  platform: 'node',
  // ESM to match the root package.json "type": "module" that the emitted
  // api/*.js inherits. Emitting CJS here would fail on `export` parsing.
  format: 'esm',
  target: 'node22',
  external,
  // Node builtins referenced via bare specifiers (node:fs etc.) resolve fine.
  banner: {
    js: '// GENERATED by scripts/buildVercelFunction.mjs — do not edit, do not commit.',
  },
  logLevel: 'info',
});

if (!existsSync(OUT)) {
  console.error(`[buildVercelFunction] expected output missing: ${OUT}`);
  process.exit(1);
}

console.log(`[buildVercelFunction] ok — ${OUT}`);
